name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checking out most recent version of code
      uses: actions/checkout@v1
      
    - name: Using Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
        
    - name: Clean npm install
      run: npm ci
      
    - name: Unit tests
      run: npm test
      
    - uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '11'  # See https://hub.docker.com/_/postgres for available versions
        postgresql db: 'abet_system_test'
        postgresql user: 'postgres'
        postgresl password: 'ukySb3rt*&87'
